mutfile <- '/mnt/trcanmed/snaketree/prj/AF_spectra/dataset/CRC1307_mutect_nobin/CRC1307-02-1-E.var_cnv.tsv.gz'
muts <- read.table(gzfile(mutfile), header=FALSE, stringsAsFactors=FALSE)
colnames(muts) <- c("chr","b","e","id")
muts$cn <- sapply(muts$id, function(x) { strsplit(x, ":")[[1]][8]})
muts$cn <- as.numeric(muts$cn)
maxcn <- 4
head(muts)
muts$cn <- factor(muts$cn, levels=seq(1, maxcn))
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()
muts <- read.table(gzfile(mutfile), header=FALSE, stringsAsFactors=FALSE)
colnames(muts) <- c("chr","b","e","id")
muts$af <- as.numeric(sapply(muts$id, function(x) { strsplit(x, ":")[[1]][7]}))
muts$cn <- sapply(muts$id, function(x) { strsplit(x, ":")[[1]][8]})
muts$cn <- as.numeric(muts$cn)
muts <- muts[muts$cn <= maxcn,]
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()
head(muts)
muts$cn <- factor(muts$cn, levels=seq(1, maxcn))
head(muts)
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()
ggplot(data=muts, aes(x=af, y=..count.., fill=cn)) + geom_density(position="identity")+theme_bw()
ggplot(data=muts, aes(x=af, y=..count.., fill=cn, alpha=0.7)) + geom_density(position="identity")+theme_bw()
ggplot(data=muts, aes(x=af, y=..count.., fill=cn)) + geom_density(aes(alpha=0.7),position="identity")+theme_bw()
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()+theme(text=element_text(size=20))
#ggplot(data=muts, aes(x=af, y=..count.., fill=cn)) + geom_density(position="identity")+theme_bw()
maxcn
maxcn <- 3
muts <- read.table(gzfile(mutfile), header=FALSE, stringsAsFactors=FALSE)
colnames(muts) <- c("chr","b","e","id")
muts$af <- as.numeric(sapply(muts$id, function(x) { strsplit(x, ":")[[1]][7]}))
muts$cn <- sapply(muts$id, function(x) { strsplit(x, ":")[[1]][8]})
muts$cn <- as.numeric(muts$cn)
muts <- muts[muts$cn <= maxcn,]
muts$cn <- factor(muts$cn, levels=seq(1, maxcn))
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity")+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_density(position="identity")+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_density(position="identity", aes(size=3))+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_density(position="identity", aes(size=2))+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_density(position="identity", size=0.5)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_density(position="identity", size=0.8)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, y=..count.., color=cn)) + geom_density(position="identity", size=0.8)+theme_bw()+theme(text=element_text(size=20))
muts$naf <- muts$af * muts$cn
muts$cn <- as.numeric(muts$cn)
muts$naf <- muts$af * muts$cn
muts$cn <- factor(muts$cn, levels=seq(1, maxcn))
cat(dim(muts))
cat("\n")
muts <- muts[muts$naf <=1,]
cat(dim(muts))
cat("\n")
ggplot(data=muts, aes(x=naf)) + geom_density(size=0.8)+theme_bw()+theme(text=element_text(size=20))+xlab('normalized af')
getwd)
getwd()
ggplot(data=muts, aes(x=naf,y=..count..)) + geom_density(size=0.8)+theme_bw()+theme(text=element_text(size=20))+xlab('normalized af')
nrom(muts)
nrow(muts)
ggplot(data=muts, aes(x=naf)) + geom_histogram(size=0.8)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, color=cn)) + geom_histogram(size=0.8)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, fill=cn), alpha=0.7) + geom_histogram(size=0.8)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, fill=cn)) + geom_histogram(size=0.8, alpha=0.5, bins=60)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, fill=cn)) + geom_histogram(size=0.8, bins=60)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, fill=cn)) + geom_histogram(size=0.8)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=af, fill=cn)) + geom_histogram(size=0.8, bins=120)+theme_bw()+theme(text=element_text(size=20))
dim(nrows)
dim(muts)
ggplot(data=muts, aes(x=naf)) + geom_histogram(size=0.8, bins=120)+theme_bw()+theme(text=element_text(size=20))
ggplot(data=muts, aes(x=naf)) + geom_histogram(size=0.8, bins=60)+theme_bw()+theme(text=element_text(size=20))
