import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')
ANNOVAR=SNAKE_ROOT+"/task/variant_annotations/dataset/annovar/hg38/humandb/"
HROOT='/home/egrassi'
BIN_DIR=PRJ_ROOT+"/local/bin"
SRC_DIR=PRJ_ROOT+"/local/src"

###################################################################
KIND="SNV" # | indel
MULTI="nomulti"
### sample variable portion #############################################
DATA=PRJ_ROOT+"/local/share/data/CRC1078_clones_all"
SDATA=DATA
SAMPLES1=['CRC1078-02-0', 'CRC1078-07-0', 'CRC1078-09-0','CRC1078-02-1-C', 'CRC1078-02-1-D', 'CRC1078-02-1-E', 'CRC1078-07-1-A', 'CRC1078-07-1-E', 'CRC1078-07-1-F', 'CRC1078-09-1-B', 'CRC1078-09-1-C', 'CRC1078-09-1-D', 'CRC1078-02-MI-A', 'CRC1078-02-MI-C', 'CRC1078-02-MI-E']
SAMPLES=['CRC1078-07A-2-4', 'CRC1078-07A-2-3', 'CRC1078-07A-2-2']+SAMPLES1
SAMPLES = list(set(SAMPLES))
SAMPLES.sort()

CLONE7=['CRC1078-07-1-A', 'CRC1078-07A-2-4', 'CRC1078-07A-2-3', 'CRC1078-07A-2-2']
CLONES=[CLONE7]
STARTTIME='-1'
TIME='-2-'
FUN_OV=find_pairs_raw_ov_stupid

SAMPLES_ORIG_T1= {
    'CRC1078-07': 'CRC1078-07-1-A',
}

SAMPLES_TREE= {
    'CRC1078-07': CLONE7
}
#SAMPLES_HIGH=["CRC1502-03","CRC1502-10","CRC1502-09","CRC1502-08"]
SAMPLES_HIGH=list(SAMPLES_ORIG_T1.keys())
SAMPLES_ZERO=[x+'-1' for x in SAMPLES_HIGH]
VCF_DIR=PRJ_ROOT+"/dataset/CRC1078_clones_all/platypus_nobin"
BULKNAME="CRC1078LMO-0-B.pass.vcf.gz"
NORMAL="CRC1078NLH0000000000D08000"
SHIPMENT="second_shipment_bulk"
##############################################################

VCFTOBED=BIN_DIR+"/vcf_to_bed_platypus"
VCFTOBED1=BIN_DIR+"/vcf_to_bed"
CNLEN=BIN_DIR+"/cn_len_plot"
CNLEN2=BIN_DIR+"/cn_len_plot2"

DBSNP=BIOINFO_ROOT+"/task/annotations/dataset/gnomad/chr_All_20180418.vcf.bgz"
CALLABLE=DATA+"/callable_covered.bed.gz"

DNDSCV_RDA=DATA+"/../RefCDS_human_GRCh38.p12.rda"

ALL_SAMPLES=SAMPLES
SAMPLE =  "wildcards" #"^1740D" for biodiversa calls #"{wildcards.sample}" for mutect # "TUMOR" for varscan
WANTED_CN = "1,2,3"

wildcard_constraints:
    sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"   
wildcard_constraints:
    t1sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"
wildcard_constraints:
    t0sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"
wildcard_constraints:
    bsample="[a-zA-Z0-9]+-[0-9]+"


# rule process_vcf_special:
#     input: vcf=DATA+"/"+SAMPLES[0]+".pass.vcf.gz", chrs=DATA+"/chrs"  
#     output: SAMPLES[0]+".tsv.gz"
#     params: tool=VCFTOBED1, multi=MULTI, kind=KIND, sample="CRC1307LMO"
#     log: SAMPLES[0]+".multiallelic"
#     shell:
#         """
#             bcftools view -s {params.sample} {input.vcf} | bcftools annotate -I +'%CHROM:%POS:%REF:%ALT' - \\
#             | grep -v "^#" |  filter_1col 1 {input.chrs} | {params.tool} {params.kind} {params.multi} 2> {log} | gzip > {output}
#         """

# ruleorder: process_vcf_special > process_vcf

## bbad llama
#egrassi@godot:/scratch/trcanmed/AF_spectra/dataset/CRC0441/platypus_nobin$ mv CRC0441-01-MI-B_CRC0441-01-0.gain.vcf.gz  vivo.merged.vcf.gz
