import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
BIN_DIR=PRJ_ROOT+"/local/bin"
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')

VCF_DIR=PRJ_ROOT+"/dataset/CRC0327/platypus_nobin"
CALLABLE=PRJ_ROOT+"/local/share/data/CRC0327/callable_covered.bed.gz"

BED=PRJ_ROOT+"/local/share/data/mutational_patterns/data"

SAMPLES=['CRC0327-08-0', 'CRC0327-02-0', 'CRC0327-04-0', 'CRC0327-02-1-A', 'CRC0327-02-1-E', 'CRC0327-02-1-I', 'CRC0327-04-1-A', 'CRC0327-04-1-B', 'CRC0327-04-1-C', 'CRC0327-08-1-A', 'CRC0327-08-1-C', 'CRC0327-08-1-F']# 'CRC0327-02-MA-B', 'CRC0327-02-MA-C', 'CRC0327-02-MC-B', 'CRC0327-02-MA-E', 'CRC0327-02-MC-C', 'CRC0327-02-MC-D', 'CRC0327-02-MI-C', 'CRC0327-02-MI-E']

BULK=['']
# TODO FIXME
CLONE8=['CRC0327-08-0', 'CRC0327-08-1-A', 'CRC0327-08-1-C', 'CRC0327-08-1-F']
CLONE2=['CRC0327-02-0', 'CRC0327-02-1-A', 'CRC0327-02-1-E', 'CRC0327-02-1-I']# 'CRC0327-02-MA-B', 'CRC0327-02-MA-C', 'CRC0327-02-MC-B', 'CRC0327-02-MA-E', 'CRC0327-02-MC-C', 'CRC0327-02-MC-D', 'CRC0327-02-MI-C', 'CRC0327-02-MI-E']
CLONE9=['CRC0327-04-0', 'CRC0327-04-1-A', 'CRC0327-04-1-B', 'CRC0327-04-1-C']

ALL_SAMPLES=SAMPLES
SAMPLE =  "wildcards" #"^1740D" for biodiversa calls #"{wildcards.sample}" for mutect # "TUMOR" for varscan
WANTED_CN = "1,2,3"

wildcard_constraints:
    sample="[a-zA-Z0-9]+-[0-9]+-[A-Z0-9]+-?[A-Z0-9]?"   
wildcard_constraints:
    t1sample="[a-zA-Z0-9]+-[0-9]+-[A-Z0-9]+-?[A-Z0-9]?"
wildcard_constraints:
    t0sample="[a-zA-Z0-9]+-[0-9]+-[A-Z0-9]+-?[A-Z0-9]?"

SAMPLES_HIGH=["CRC0327-08","CRC0327-02","CRC0327-04"] # list comprehens TODO
SAMPLES_ZERO=[x+'-0' for x in SAMPLES_HIGH]

WANTED_CN = "1,2,3"
# right now manually determined
NSIGN=4
