import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
BIOINFO_ROOT = os.getenv('BIOINFO_ROOT')
SNAKE_ROOT=os.getenv('SNAKE_ROOT')
ANNOVAR=SNAKE_ROOT+"/task/variant_annotations/dataset/annovar/hg38/humandb/"
HROOT='/home/egrassi'
BIN_DIR=PRJ_ROOT+"/local/bin"
SRC_DIR=PRJ_ROOT+"/local/src"

###################################################################
KIND="indel" # | indel
MULTI="nomulti"
### sample variable portion #############################################
DATA=PRJ_ROOT+"/local/share/data/CRC0327_clones_all"
SDATA=DATA
SAMPLES=['CRC0327-08-0', 'CRC0327-02-0', 'CRC0327-04-0', 'CRC0327-02-1-A', 'CRC0327-02-1-E', 'CRC0327-02-1-I', 'CRC0327-04-1-A', 'CRC0327-04-1-B', 'CRC0327-04-1-C', 'CRC0327-08-1-A', 'CRC0327-08-1-C', 'CRC0327-08-1-F', 'CRC0327-02-MA-B', 'CRC0327-02-MA-C', 'CRC0327-02-MC-B', 'CRC0327-02-MA-E', 'CRC0327-02-MC-C', 'CRC0327-02-MC-D', 'CRC0327-02-MI-C', 'CRC0327-02-MI-E']
SAMPLES=SAMPLES+['CRC0327-02-MC2-D', 'CRC0327-02-MC2-C', 'CRC0327-02-MC2-B', 'CRC0327-02-MA2-G', 'CRC0327-02-MA2-E', 'CRC0327-02-MA2-B']
SAMPLES = list(set(SAMPLES))
SAMPLES.sort()

CLONE8=['CRC0327-08-0', 'CRC0327-08-1-A', 'CRC0327-08-1-C', 'CRC0327-08-1-F']
CLONE2=['CRC0327-02-0', 'CRC0327-02-1-A', 'CRC0327-02-1-E', 'CRC0327-02-1-I', 'CRC0327-02-MA-B', 'CRC0327-02-MA-C', 'CRC0327-02-MC-B', 'CRC0327-02-MA-E', 'CRC0327-02-MC-C', 'CRC0327-02-MC-D', 'CRC0327-02-MI-C', 'CRC0327-02-MI-E',
'CRC0327-02-MC2-D', 'CRC0327-02-MC2-C', 'CRC0327-02-MC2-B', 'CRC0327-02-MA2-G', 'CRC0327-02-MA2-E', 'CRC0327-02-MA2-B']
CLONE4=['CRC0327-04-0', 'CRC0327-04-1-A', 'CRC0327-04-1-B', 'CRC0327-04-1-C']
CLONES=[CLONE8, CLONE2, CLONE4]

# This is commented out because this second round in vivo was not cloned after the first six months, its T0 is the original one and
# the original code should be able to take care of it.
#STARTTIME='-1'
#TIME='-2-'
#FUN_OV=find_pairs_raw_ov_stupid

#SAMPLES_ORIG_T1= {
#    'CRC0327-08': 'CRC1502-03-1-A',
#}

#SAMPLES_TREE= {
#    'CRC0327-08': CLONE8,
#}
SAMPLES_HIGH=["CRC0327-04","CRC0327-02","CRC0327-08"]
#SAMPLES_HIGH=list(SAMPLES_ORIG_T1.keys())
SAMPLES_ZERO=[x+'-0' for x in SAMPLES_HIGH]
VCF_DIR=PRJ_ROOT+"/dataset/CRC0327_clones_all/platypus_nobin"
BULKNAME="CRC0327LMO-0-B"
NORMAL="CRC0327NLH0000000000D04000"
SHIPMENT="second_shipment_bulk"
##############################################################

VCFTOBED=BIN_DIR+"/vcf_to_bed_platypus"
VCFTOBED1=BIN_DIR+"/vcf_to_bed"
CNLEN=BIN_DIR+"/cn_len_plot"
CNLEN2=BIN_DIR+"/cn_len_plot2"

DBSNP=BIOINFO_ROOT+"/task/annotations/dataset/gnomad/chr_All_20180418.vcf.bgz"
CALLABLE=DATA+"/callable_covered.bed.gz"

DNDSCV_RDA=DATA+"/../RefCDS_human_GRCh38.p12.rda"

ALL_SAMPLES=SAMPLES
SAMPLE =  "wildcards" #"^1740D" for biodiversa calls #"{wildcards.sample}" for mutect # "TUMOR" for varscan
WANTED_CN = "1,2,3"

wildcard_constraints:
    sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"   
wildcard_constraints:
    t1sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"
wildcard_constraints:
    t0sample="[a-zA-Z0-9]+-[0-9A-Z]+-[A-Z0-9]+-?[A-Z0-9]?"
wildcard_constraints:
    bsample="[a-zA-Z0-9]+-[0-9]+"


# rule process_vcf_special:
#     input: vcf=DATA+"/"+SAMPLES[0]+".pass.vcf.gz", chrs=DATA+"/chrs"  
#     output: SAMPLES[0]+".tsv.gz"
#     params: tool=VCFTOBED1, multi=MULTI, kind=KIND, sample="CRC1307LMO"
#     log: SAMPLES[0]+".multiallelic"
#     shell:
#         """
#             bcftools view -s {params.sample} {input.vcf} | bcftools annotate -I +'%CHROM:%POS:%REF:%ALT' - \\
#             | grep -v "^#" |  filter_1col 1 {input.chrs} | {params.tool} {params.kind} {params.multi} 2> {log} | gzip > {output}
#         """

# ruleorder: process_vcf_special > process_vcf

## bbad llama
#egrassi@godot:/scratch/trcanmed/AF_spectra/dataset/CRC0441/platypus_nobin$ mv CRC0441-01-MI-B_CRC0441-01-0.gain.vcf.gz  vivo.merged.vcf.gz
